name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPO: team/banking-app-repo
  TF_WORKING_DIR: terraform

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: codebuild-mycustomrunner-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      #########################################
      # 1. Checkout Code
      #########################################
      - name: Checkout repository
        uses: actions/checkout@v4

      #########################################
      # 2. Set IMAGE_TAG as Commit SHA
      #########################################
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      #########################################
      # 3. Configure AWS Credentials
      #########################################
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      #########################################
      # 4. Login to Amazon ECR
      #########################################
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      #########################################
      # 5. Build and Push Docker Image
      #########################################
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd app
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} .
          docker push $ECR_REGISTRY/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}


      #########################################
      # 6. Setup Terraform
      #########################################
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      #########################################
      # 7. Terraform Init
      #########################################
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -reconfigure

      #########################################
      # 8. Terraform Plan
      #########################################
      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -var="image_tag=${{ env.IMAGE_TAG }}" -out=tfplan

      #########################################
      # 9. Terraform Apply (Auto-approve)
      #########################################
      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan
